export const mockData = [
  {
    ReleaseTime: null,
    FlowAmount: 0,
    SiteUrl: null,
    BlockChainUrl: null,
    WhitePaperUrl: null,
    Name: 'USDT',
    Context: '',
    LanguageType: null,
    SortNumber: 1,
    IsRelease: null,
    CreateID: null,
    CreateTime: '0001-01-01',
    Keywords: null,
    IsRecommend: null,
    WebSiteID: null,
    FullName: 'USDT',
    Blockchain: 0,
    TotalAmount: 0,
    IconA: null,
    IconB: null,
    Seotitle: null,
    Seokeywords: null,
    Seodescription: null,
    sortName: null,
    sortOrder: null,
    SearchStartTime: null,
    SearchEndTime: null,
    Id: '30649305172323123236c6',
  },
  {
    ReleaseTime: '2008-10-31 00:00:00',
    FlowAmount: 19024268,
    SiteUrl: 'https://bitcoin.org',
    BlockChainUrl: 'https://www.blockchain.com/explorer',
    WhitePaperUrl: 'https://bitcoin.org/bitcoin.pdf',
    Name: 'BTC',
    Context:
      '<p>比特币(BTC)是一种点对点加密货币，旨在充当独立于任何中央机构的一种交易手段。 BTC可以安全，可验证和不变的方式进行电子现金转移。</p><p>BTC于2009年推出，是通过在交易信息广播到比特币网络中的所有节点之前加盖交易时间戳的"第一种解决双重支出问题的虚拟数字货币"。比特币协议通过blockchain网络结构为拜占庭容错问题提供了解决方案，该概念最初由Stuart Haber和W. Scott Stornetta创建1991年。</p><p>Bitcoin的白皮书于由个人或一个团体以化名"Satoshi Nakamoto"于2008年发表，其基本身份尚未得到验证。</p><p>比特币协议使用基于SHA-256d的工作量证明(PoW)算法达成网络共识。其网络的目标出块时间为10分钟，最大供应量为2100万个代币，代币的产生速率不断下降。为了防止拥堵时间的波动，通过基于过去2016年拥堵时间的算法重新调整了网络的出块难度。</p><p>区块大小上限为1兆字节，比特币协议同时支持Lightning Network支付渠道的多层基础结构，以及隔离见证，这是一个增加功能的软分叉作为网络可扩展性的解决方案。</p>',
    LanguageType: null,
    SortNumber: 2,
    IsRelease: null,
    CreateID: null,
    CreateTime: '0001-01-01',
    Keywords: null,
    IsRecommend: null,
    WebSiteID: null,
    FullName: 'Bitcoin',
    Blockchain: 0,
    TotalAmount: 21000000,
    IconA: null,
    IconB: null,
    Seotitle: null,
    Seokeywords: null,
    Seodescription: null,
    sortName: null,
    sortOrder: null,
    SearchStartTime: null,
    SearchEndTime: null,
    Id: '1xx3-k3olkGgIwEiPqwXMw',
  },
  {
    ReleaseTime: '2014-07-24 00:00:00',
    FlowAmount: 120500593,
    SiteUrl: 'https://ethereum.org/en/',
    BlockChainUrl: 'https://etherscan.io/',
    WhitePaperUrl: 'https://github.com/ethereum/wiki/wiki/White-Paper',
    Name: 'ETH',
    Context:
      '<p>以太坊由俄罗斯裔加拿大程序员Vitalik Buterin于2015年创建。该平台基于去中心化原则，这意味着它不受任何单一实体控制。</p><p>以太坊允许用户构建和部署软件（通常以Dapp的形式），然后由所有运行以太坊的全球分布式计算机网络提供支持。以太坊网络是去中心化的，这一点使其能够高度抵抗任何形式的审查或停机。</p><p>此外，以太坊是一个开源区块链平台，使用其原生货币（称为Ether或ETH，以太币）运行。所有网络交易费用或燃料费均以ETH支付。</p><p>以太币(ETH)是以太坊区块链专门用于支付交易费用的代币。这种代币负责为网络中发生的几乎所有事情提供支持。</p><p>任何人都可以使用以太坊网络来创建和运行智能合约，这些智能合约是自主运行的软件程序，无需用户干预。以太坊的增长一定程度上可以归功于其智能合约功能，这使得Dapp、非同质化代币(NFT)等生态系统不断发展。</p><p>上海升级为以太坊平台带来了一系列技术提升。其中引入的一项主要功能是用户能够访问和取消质押以太坊代币。这些代币此前由信标链的验证者锁定在智能合约中。</p><p>上海升级之前，如果用户要成为采用权益证明(PoS)的以太坊区块链验证者，则需将代币锁定在智能合约中，从而无法自由访问或转账这些代币。但最新升级后，以太坊用户现在可以选择按需取消质押代币，从而能更自如地掌控个人资产。</p>',
    LanguageType: null,
    SortNumber: 3,
    IsRelease: null,
    CreateID: null,
    CreateTime: '0001-01-01',
    Keywords: null,
    IsRecommend: null,
    WebSiteID: null,
    FullName: 'Ethereum',
    Blockchain: 0,
    TotalAmount: 120500593,
    IconA: null,
    IconB: null,
    Seotitle: null,
    Seokeywords: null,
    Seodescription: null,
    sortName: null,
    sortOrder: null,
    SearchStartTime: null,
    SearchEndTime: null,
    Id: 'APqFnATs2U6oYPFxJjAooQ',
  },
  {
    ReleaseTime: '2017-07-08 00:00:00',
    FlowAmount: 144005886,
    SiteUrl: 'https://www.bnbchain.org/en',
    BlockChainUrl: 'https://explorer.bnbchain.org/',
    WhitePaperUrl: 'https://whitepaper.io/document/10/binance-whitepaper',
    Name: 'BNB',
    Context:
      '<p>币安币(BNB)是为整个BNB Chain生态系统提供支持的加密货币，也是BNB信标链和BNB Smart Chain的原生代币，可在币安加密货币交易平台上付款交易。</p><p>作为全球最热门的效用代币之一，币安币用例丰富，用途广泛。</p><p>BNB通过2017年6月26日至7月3日举行的首次代币发行（简称“ICO”）活动问世。11天后，币安交易平台正式开放交易。它的初始发行价格为1 ETH和1 BTC可分别兑换2,700 BNB和20,000 BNB。虽然BNB通过ICO发行，但BNB的持有者并非币安的股东，也不是币安的投资人。</p><p>BNB在BNB Chain生态系统内外都具有广泛用途。BNB最初以ERC-20代币形式发行在以太坊区块链，但现已转移到BNB Chain主链。BNB的初始总供应量为2亿枚，后经多次销毁，数量逐渐下降。BNB的现价可在币安实时获取和更新。</p>',
    LanguageType: null,
    SortNumber: 5,
    IsRelease: null,
    CreateID: null,
    CreateTime: '0001-01-01',
    Keywords: null,
    IsRecommend: null,
    WebSiteID: null,
    FullName: 'BNB',
    Blockchain: 0,
    TotalAmount: 144005886,
    IconA: null,
    IconB: null,
    Seotitle: null,
    Seokeywords: null,
    Seodescription: null,
    sortName: null,
    sortOrder: null,
    SearchStartTime: null,
    SearchEndTime: null,
    Id: 'BSCnATs2U6oYPFxJjAooQ',
  },
  {
    ReleaseTime: '2017-07-02 08:00:00',
    FlowAmount: 17496900,
    SiteUrl: 'https://bch.info/en/',
    BlockChainUrl: 'https://blockchair.com/bitcoin-cash',
    WhitePaperUrl: 'https://bitcoincash.org/bitcoin.pdf',
    Name: 'BCH',
    Context:
      '<p>比特现金（BCH）全称为Bitcoin Cash，是矿池ViaBTC基于Bitcoin ABC方案推出的新的加密数字资产。 2017年7月21日，比特币分叉方案BIP91已经获得全网算力支持，一致同意先进行隔离见证升级，并在之后的6个月内把底层区块链的区块大小升级至2M。然而“搅局者”出现了——挖矿巨头比特币大陆旗下的矿池ViaBTC准备了一套硬分叉的体系，基于比特币的原链推出“比特币现金”。 项目亮点 链上扩容 - 比特币现金遵循中本聪通过链上扩容实现全球普及的路线图。作为第一步，区块大小限制已被设为可调整，默认提升到了 8MB 。 允许未来大幅提升区块容量的研究正在进行 。 新的交易签名 - 新的签名哈希 (SigHash) 类型提供了重放攻击保护、改善了硬件钱包安全性，也解决了二次哈希问题。 新的难度调整算法(DAA) - 响应式的工作量证明(PoW) 难度调整允许矿工按其意愿从旧的比特币链迁移至新链，同时提供保护抑制算力过度波动。 去中心化的开发 - 有数个独立开发团队提供的软件实现，未来是安全的。比特币现金能够抵御在协议开发上的政治和社交攻击，没有单独的团队或项目能控制。bitcoin-ml 邮件列表是一个好的平台，用于跨发开团队协作以实现协议变更。</p>',
    LanguageType: null,
    SortNumber: 1000,
    IsRelease: null,
    CreateID: null,
    CreateTime: '0001-01-01',
    Keywords: null,
    IsRecommend: null,
    WebSiteID: null,
    FullName: 'Bitcoin Cash',
    Blockchain: 0,
    TotalAmount: 21000000,
    IconA: null,
    IconB: null,
    Seotitle: null,
    Seokeywords: null,
    Seodescription: null,
    sortName: null,
    sortOrder: null,
    SearchStartTime: null,
    SearchEndTime: null,
    Id: 'NEW9966DwP0awKT0BCHABC',
  },
  {
    ReleaseTime: '0001-01-01 00:00:00',
    FlowAmount: 0,
    SiteUrl: 'https://ethereumpow.org/',
    BlockChainUrl: 'https://www.oklink.com/en/ethw/',
    WhitePaperUrl: null,
    Name: 'ETHW',
    Context:
      '<p>EthereumPoW（ETHW）是由非官方社区开发者主导分叉出的基于Proof of Work共识机制的以太坊，是Ethereum（ETH）的分叉币。</p>',
    LanguageType: null,
    SortNumber: 1000,
    IsRelease: null,
    CreateID: null,
    CreateTime: '0001-01-01',
    Keywords: null,
    IsRecommend: null,
    WebSiteID: null,
    FullName: 'EthereumPoW',
    Blockchain: 0,
    TotalAmount: 0,
    IconA: null,
    IconB: null,
    Seotitle: null,
    Seokeywords: null,
    Seodescription: null,
    sortName: null,
    sortOrder: null,
    SearchStartTime: null,
    SearchEndTime: null,
    Id: '35963895095117004888fa',
  },
  {
    ReleaseTime: '2020-10-15 00:00:00',
    FlowAmount: 234590008,
    SiteUrl: 'https://filecoin.io/zh-cn/',
    BlockChainUrl: 'https://filfox.info/zh',
    WhitePaperUrl: 'https://filecoin.io/zh-cn/',
    Name: 'FIL',
    Context:
      '<p><span style="color: rgb(34, 34, 34);">FIL 是Filecoin区块网络的存储代币。Filecoin是旨在存储人类社会重要信息的分布式网络。Filecoin和点对点分布式网络协议IPFS相结合，形成一个不需受企业控制而更加高效且安全的网络。Filecoin网络将允许任何人成为存储提供商并以为业务竞争的方式来实现规模经济。内容寻址和加密存储证明可确保数据在长久的时间范围内被安全、正确地存储。Filecoin网络将拥有大量存储提供者和开发者，从而造就强大且不断改进的服务。加密证明可确保您的数据长时间内持续可用且不会被更改。Filecoin可以成为重要公共数据的基础， 如可公开访问的科学数据、创新大众媒体、历史档案和存档等等。Filecoin将降低存储提供者的入门门槛并将云存储变成商品。 这就使新的市场进入者可以轻松地与原有参与者竞争。存储提供者会为了您的需求进行激烈竞争，以最优价格存储您的数据并提供灵活的选择。而这一切都是在透明的全球市场上完成的。Filecoin为IPFS添加了激励性的永久的存储。Filecoin主网上线后IPFS用户可以直接可靠地存储其数据在Filecoin上，从而为网络打开了众多应用程序和落地场景的大门。</span></p>',
    LanguageType: null,
    SortNumber: 1000,
    IsRelease: null,
    CreateID: null,
    CreateTime: '0001-01-01',
    Keywords: null,
    IsRecommend: null,
    WebSiteID: null,
    FullName: 'Filecoin',
    Blockchain: 0,
    TotalAmount: 2000000000,
    IconA: null,
    IconB: null,
    Seotitle: null,
    Seokeywords: null,
    Seodescription: null,
    sortName: null,
    sortOrder: null,
    SearchStartTime: null,
    SearchEndTime: null,
    Id: '534fdlkGgIwEiPqwXMw',
  },
  {
    ReleaseTime: '2017-09-21 00:00:00',
    FlowAmount: 638099970,
    SiteUrl: 'https://chain.link/',
    BlockChainUrl:
      'https://solscan.io/token/CWE8jPTUYhdCTZYWPTe1o5DFqfdjzWKc9WKz6rSjQUdG',
    WhitePaperUrl: 'https://chain.link/whitepaper',
    Name: 'LINK',
    Context:
      '<p>Chainlink于2017年6月由旧金山金融科技公司SmartContract推出，开发商将其描述为一种安全区块链中间件，旨在通过允许智能合约访问关键链外资源（例如数据流（数据库）、网站（微信， 淘宝等）API、 和传统的银行（支付宝、微信支付等）账户支付。</p><p>ChainLink网络是ChainLink节点的分布式网络，它们都直接将特定数据、API和各种离线支付功能的使用输送给智能合约。</p><p>Chainlink网络由两个独立的部分组成，链上链和外链，它们必须交互以提供服务。该网络的构建方式使其可以升级，因此可以在更好的技术和技术出现时替换其不同的组件。网络的链上组件通过服务级别协议（SLA）基于智能合约的一方请求的度量来过滤神谕。使用这些指标，Chainlink收集对SLA查询的响应，使用声誉和聚合模型对它们进行排序，并提供可能实施到智能合约中的Chainlink查询的最终集合结果。</p><p>Chainlink的代币LINK销售上限为3200万美元，总供应量为10亿。所有LINK代币中有35％会通过节点运营商来激励生态系统，并在公开代币销售中额外销售35％。LINK代币总数中的最后30％将留在公司继续开发和员工支付。</p>',
    LanguageType: null,
    SortNumber: 1000,
    IsRelease: null,
    CreateID: null,
    CreateTime: '0001-01-01',
    Keywords: null,
    IsRecommend: null,
    WebSiteID: null,
    FullName: 'ChainLink Token',
    Blockchain: 0,
    TotalAmount: 1000000000,
    IconA: null,
    IconB: null,
    Seotitle: null,
    Seokeywords: null,
    Seodescription: null,
    sortName: null,
    sortOrder: null,
    SearchStartTime: null,
    SearchEndTime: null,
    Id: 'NEW8888DwP0awK00ULINK',
  },
  {
    ReleaseTime: '2011-10-08 00:00:00',
    FlowAmount: 75428112,
    SiteUrl: 'https://litecoin.org/',
    BlockChainUrl: 'https://blockchair.com/litecoin',
    WhitePaperUrl: null,
    Name: 'LTC',
    Context:
      '<p>莱特币(Litecoin)是一种基于“点对点”(peer-to-peer)技术的网络货币，其受到了比特币(<span style="color: rgb(89, 143, 207);">BTC</span>)的启发，并且在技术上具有相同的实现原理。它不同于比特币的地方在于，通过消费级的硬件也可以高效地“挖矿”，提供更快速的交易确认(平均2.5分钟)。莱特币网络预期将生产8400万个货币单位。</p><p>随着比特币的火爆，全球涌现出了大量“山寨”比特币的电子货币。截至目前，世界各地已经存在至少30种其他的电子货币，如莱特币、质数币、比奥币、瑞波币、招财币、美卡币等等。这些山寨币中名气最大的就是莱特币，业界甚至还流传着“比特黄金，莱特银”的说法。</p><p>莱特币的创造者Charlie Lee毕业于麻省理工大学，曾经是Google的员工。他于2011年设计了莱特币。</p><p>莱特币受到了比特币的启发，并且在技术上具有相同的实现原理，莱特币的创造和转让基于一种开源的加密协议，不受到任何中央机构的管理。</p>',
    LanguageType: null,
    SortNumber: 1000,
    IsRelease: null,
    CreateID: null,
    CreateTime: '0001-01-01',
    Keywords: null,
    IsRecommend: null,
    WebSiteID: null,
    FullName: 'Litecoin',
    Blockchain: 0,
    TotalAmount: 84000000,
    IconA: null,
    IconB: null,
    Seotitle: null,
    Seokeywords: null,
    Seodescription: null,
    sortName: null,
    sortOrder: null,
    SearchStartTime: null,
    SearchEndTime: null,
    Id: 'CPqFnATs2U6oYPFxJjAooQ',
  },
  {
    ReleaseTime: '2017-08-31 00:00:00',
    FlowAmount: 86160208764,
    SiteUrl: 'https://trondao.org/',
    BlockChainUrl: 'https://tronscan.org/#/',
    WhitePaperUrl: 'https://developers.tron.network/docs/getting-start',
    Name: 'TRX',
    Context:
      '<p>波场TRON以推动互联网去中心化为己任，致力于为去中心化互联网搭建基础设施。旗下的TRON协议是全球最大的基于区块链的去中心化应用操作系统协 议之一，为协议上的去中心化应用运行提供高吞吐，高扩展，高可靠性的底层公链支持。波场TRON还通过创新的可插拔智能合约平台为以太坊智能合约提供更好的兼容性。</p><p>自2018年7月24日起，TRON收购了位于旧金山的互联网技术公司BitTorrent Inc.。 BitTorrent Inc.设计的分布式技术能够有效扩展，保持智能化，并使创作者和消费者能够控制其内容和数据。 每个月有超过1.7亿人使用BitTorrent Inc.开发的产品。 BitTorrent Inc.的协议每天可以传输全球40％的互联网流量。</p>',
    LanguageType: null,
    SortNumber: 1000,
    IsRelease: null,
    CreateID: null,
    CreateTime: '0001-01-01',
    Keywords: null,
    IsRecommend: null,
    WebSiteID: null,
    FullName: 'TRON',
    Blockchain: 0,
    TotalAmount: 86160154096,
    IconA: null,
    IconB: null,
    Seotitle: null,
    Seokeywords: null,
    Seodescription: null,
    sortName: null,
    sortOrder: null,
    SearchStartTime: null,
    SearchEndTime: null,
    Id: '6LTTBZwKYUS7xbpaNjR2pg',
  },
]
