export const coinList = [
  {
    coin: 'USDT',
    name: 'USDT',
    icon: 'https://img.idcs.io/tenants/12A9904584E555B10EA2ED6258D7C1EE/OtherFile66204112.png',
    isEnableRecharge: true,
    isEnableWithdraw: true,
    coinType: 0,
    protocols: [
      {
        coinId: 'bPqFnATs2U6oYPFxJjAooQ',
        mainChain: 'TRX',
        mainChainId: 'ae6a0414-7e13-4354-87ed-ff55ecc78e08',
        mainSymbol: 'TRX',
        isSupportMemo: false,
        quantityPrecision: 0.000001,
        quantityPrecisionDisplay: 6,
        minRechargeQuantity: 0.01,
        minWithdrawQuantity: 10,
        withdrawFee: 1,
        withdrawAuditQuantity: 2000,
        singleMaxWithdrawQuantity: 5000000,
        dayMaxWithdrawQuantity: 1200000,
        rechargeConfirmation: 3,
        withdrawConfirmation: 3,
        rechargeDescription:
          '<p>温馨提示</p><p>•只能向该钱包地址充值&nbsp;<strong style="color: rgb(255, 62, 62);">USDT TRC20</strong>,否则将不可找回</p><p>•您充值至上述地址后，需要整个网络节点的确认，1 次网络确认后到账，1 次网络确认后可提币</p><p><span style="color: rgb(230, 0, 0);">•最小充值金額：0.01 USDT, 小于最小金额的充值将不会入账且无法退回</span></p>',
        withdrawDescription:
          '<p class="ql-align-justify"><strong>注意事项</strong></p><p class="ql-align-justify">•最低提币数量为<span style="color: rgb(225, 60, 57);">10&nbsp;USDT</span></p><p class="ql-align-justify">•手续费优先从账户余额中扣除，当余额不足以抵扣手续费时则从提币数量中扣除</p><p class="ql-align-justify">•提币手续费为<span style="color: rgb(230, 0, 0);">1&nbsp;</span><span style="color: rgb(225, 60, 57);">USDT</span></p>',
        payMethodDescription: '',
        status: 4,
        protocol: 'TRC20',
        sortNum: 1,
        withdrawalAuthValue: null,
        coinType: 0,
        rechargeFee: 0,
        rechargeRate: 0,
        withdrawRate: 0,
        maxRechargeAmount: 0,
        paymentChannelId: null,
        paymentChannel: null,
        payType: null,
      },
      {
        coinId: 'bPqFnATs2U6oYPFxJjAooQ',
        mainChain: 'TRX',
        mainChainId: 'ae6a0414-7e13-4354-87ed-ff55ecc78e08',
        mainSymbol: 'TRX',
        isSupportMemo: false,
        quantityPrecision: 0.000001,
        quantityPrecisionDisplay: 6,
        minRechargeQuantity: 0.01,
        minWithdrawQuantity: 10,
        withdrawFee: 1,
        withdrawAuditQuantity: 2000,
        singleMaxWithdrawQuantity: 5000000,
        dayMaxWithdrawQuantity: 1200000,
        rechargeConfirmation: 3,
        withdrawConfirmation: 3,
        rechargeDescription:
          '<p>温馨提示</p><p>•只能向该钱包地址充值&nbsp;<strong style="color: rgb(255, 62, 62);">USDT TRC20</strong>,否则将不可找回</p><p>•您充值至上述地址后，需要整个网络节点的确认，1 次网络确认后到账，1 次网络确认后可提币</p><p><span style="color: rgb(230, 0, 0);">•最小充值金額：0.01 USDT, 小于最小金额的充值将不会入账且无法退回</span></p>',
        withdrawDescription:
          '<p class="ql-align-justify"><strong>注意事项</strong></p><p class="ql-align-justify">•最低提币数量为<span style="color: rgb(225, 60, 57);">10&nbsp;USDT</span></p><p class="ql-align-justify">•手续费优先从账户余额中扣除，当余额不足以抵扣手续费时则从提币数量中扣除</p><p class="ql-align-justify">•提币手续费为<span style="color: rgb(230, 0, 0);">1&nbsp;</span><span style="color: rgb(225, 60, 57);">USDT</span></p>',
        payMethodDescription: '',
        status: 4,
        protocol: 'BEP20',
        sortNum: 1,
        withdrawalAuthValue: null,
        coinType: 0,
        rechargeFee: 0,
        rechargeRate: 0,
        withdrawRate: 0,
        maxRechargeAmount: 0,
        paymentChannelId: null,
        paymentChannel: null,
        payType: null,
      },
    ],
    sortNum: 0,
  },
  {
    coin: 'BTC',
    name: 'Bitcoin',
    icon: 'https://img.idcs.io/tenants/12A9904584E555B10EA2ED6258D7C1EE/OtherFile60590046.png',
    isEnableRecharge: true,
    isEnableWithdraw: true,
    coinType: 0,
    protocols: [
      {
        coinId: '1xx3-k3olkGgIwEiPqwXMw',
        mainChain: 'BTC',
        mainChainId: 'ae6a0413-ecb9-4d7f-881e-ce85b515d795',
        mainSymbol: 'BTC',
        isSupportMemo: false,
        quantityPrecision: 1e-8,
        quantityPrecisionDisplay: 8,
        minRechargeQuantity: 0.0005,
        minWithdrawQuantity: 0.001,
        withdrawFee: 0.0002,
        withdrawAuditQuantity: 6666666,
        singleMaxWithdrawQuantity: 100,
        dayMaxWithdrawQuantity: 1000,
        rechargeConfirmation: 2,
        withdrawConfirmation: 2,
        rechargeDescription:
          '<p><strong>温馨提示</strong></p><p>•只能向该钱包地址充值 <strong style="color: rgb(230, 0, 0);">BTC</strong>，否则将不可找回</p><p>•您充值至上述地址后，需要整个网络节点的确认，1次网络确认后到账，2次网络确认后可提币</p><p>•<span style="color: rgb(230, 0, 0);">最小充值金额：0.0005 BTC 小于最小金额的充值将不会入账且无法退回</span></p>',
        withdrawDescription:
          '<p class="ql-align-justify"><strong>注意事项</strong></p><p class="ql-align-justify">•最低提币数量为<span style="color: rgb(230, 0, 0);">0.01BTC</span></p><p class="ql-align-justify">•手续费优先从账户余额中扣除，当余额不足以抵扣手续费时则从提币数量中扣除</p><p class="ql-align-justify">•提币手续费为<span style="color: rgb(230, 0, 0);">0.0002BTC</span></p>',
        payMethodDescription: '',
        status: 4,
        protocol: 'BTC',
        sortNum: 2,
        withdrawalAuthValue: null,
        coinType: 0,
        rechargeFee: 0,
        rechargeRate: 0,
        withdrawRate: 0,
        maxRechargeAmount: 0,
        paymentChannelId: null,
        paymentChannel: null,
        payType: null,
      },
    ],
    sortNum: 0,
  },
]
