/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./src/components/contact/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Empty: typeof import('./src/components/empty/index.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    Label: typeof import('./src/components/label/index.vue')['default']
    Lang: typeof import('./src/components/lang/index.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Lists: typeof import('./src/components/lists/index.vue')['default']
    Notice: typeof import('./src/components/notice/index.vue')['default']
    PlusPagination: typeof import('plus-pro-components/es')['PlusPagination']
    Poster: typeof import('./src/components/poster/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rules: typeof import('./src/components/rules/index.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
